## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [17]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [18]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [28]:
from IPython.core.interactiveshell import InteractiveShell
from sklearn.model_selection import train_test_split
InteractiveShell.ast_node_interactivity='all'

x_train_1, x_test_1, y_train_1, y_test_1 = train_test_split(X[:40], y[:40], test_size=0.25)
x_train_2, x_test_2, y_train_2, y_test_2 = train_test_split(X[40:], y[40:], test_size=10)

x_train = np.vstack((x_train_1, x_train_2))
x_test = np.vstack((x_test_1, x_test_2))
y_train = np.hstack((y_train_1, y_train_2))
y_test = np.hstack((y_test_1, y_test_2))

x_test
y_test

array([[ 70,  71,  72,  73,  74],
       [165, 166, 167, 168, 169],
       [ 90,  91,  92,  93,  94],
       [ 10,  11,  12,  13,  14],
       [ 50,  51,  52,  53,  54],
       [180, 181, 182, 183, 184],
       [ 55,  56,  57,  58,  59],
       [150, 151, 152, 153, 154],
       [ 40,  41,  42,  43,  44],
       [160, 161, 162, 163, 164],
       [470, 471, 472, 473, 474],
       [735, 736, 737, 738, 739],
       [780, 781, 782, 783, 784],
       [475, 476, 477, 478, 479],
       [260, 261, 262, 263, 264],
       [885, 886, 887, 888, 889],
       [545, 546, 547, 548, 549],
       [435, 436, 437, 438, 439],
       [480, 481, 482, 483, 484],
       [840, 841, 842, 843, 844]])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])